{{- if .Values.applicationConf }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scoold.name" . }}-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ include "scoold.name" . }}
data:
  application.conf: |
{{ toYaml .Values.applicationConf | indent 4 }}
{{- end -}}